version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'vic1707'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "09:50"
      timezone: 'Europe/Paris'
    assignees:
      - 'vic1707'
